### ISSUE TITLE
About evaluation

### ISSUE THREAD

**Issue by wwxxyy1996** [ChantalMP/Rad-ReStruct#4]
Thank you for your incredible work on this project.

I am using the provided rad-restruct v1.0.0 weights (val=0.33.ckpt) and running evaluation.sh to try to reproduce the results from Table 3 in the paper. The code in evaluation.sh is 

python -m evaluation.evaluate_radrestruct --run_name "eval_radrestruct" --match_instances --batch_size 1 --use_pretrained --model_dir "/Data/Rad-ReStruct/official_model/val=0.33.ckpt" --progressive --mixed_precision

The GPU is RTX 8000.

However I obtain the results

Acc: 0.9912013682911516, Report_acc: 0.30213903743315507, F1: 0.3193866192329935, Prec: 0.6461682608335141, Rec: 0.33324154758975205
{'l1': 'F1: 0.6431 - Acc: 0.3369 - Prec: 0.8109 - Rec: 0.6458', 'l2': 'F1: 0.7164 - Acc: 0.3102 - Prec: 0.8528 - Rec: 0.7200', 'l2_diseases': 'F1: 0.7357 - Acc: 0.4813 - Prec: 0.8381 - Rec: 0.7391', 'l2_signs': 'F1: 0.7428 - Acc: 0.7193 - Prec: 0.9311 - Rec: 0.7445', 'l2_objects': 'F1: 0.6709 - Acc: 0.8743 - Prec: 0.7718 - Rec: 0.6755', 'l2_body_regions': 'F1: 0.6870 - Acc: 0.5241 - Prec: 0.8215 - Rec: 0.6956', 'l3': 'F1: 0.0410 - Acc: 0.3021 - Prec: 0.4999 - Rec: 0.0627'}

Firstly, I am a little bit confused about the report acc results in Table 3. Each level has a report acc, while the result only give one report acc. Second, the number don't match. Am I using the correct weights?

Thank you very much for your work again! It is really amazing.

**Comment by ChantalMP** [comment]
Hi :)
When comparing your results with our results, please use the results in our github readme and not in the paper. As mentioned the results in the paper are outdated by now because we updated the dataset, leading to slight differences in the results.
When comparing your results with the ones in the readme, they seem to match perfectly, so you are using the correct weights.

Regarding the report accuracy, I'm not sure if I understand your question. The report accuracy measures how many reports are entirely correct - overall this includes the entire report - if it is measured per level it only checks correctness in this specific level or topic. 

Please let me know if there is anything else unclear :)

Best, Chantal

**Comment by wwxxyy1996** [comment]
Hi Chantal :), thank you for the clarification.  Also, thanks for explaining report accuracy. I totally understand! Thank you very much! 

Best wishes.
