### ISSUE TITLE
About the no-selection"

### ISSUE THREAD

**Issue by Eldo-rado** [ChantalMP/Rad-ReStruct#5]
Hi@ChantalMP , great work, and thank you for your contribution. I have a question I’d like to clarify.

When the "no-selection" option appears in the answer, is it because the original report doesn’t include this information, for example, there is no description of the lesion’s degree/attributes? During inference, will this question still be provided to the model? If so, how is accuracy calculated during evaluation?

Thank you in advance. ☺️

**Comment by ChantalMP** [comment]
Hi @Eldo-rado,

Thanks for your question :) 

yes, exactly, the "no selection" option catches all the cases where no information was provided, which might be because it was forgotten to mention / it is not relevant but also if none of the options are correct.

Therefore we opted to treat it as any other class and expect the model to predict "no selection" in this case.

**Comment by Eldo-rado** [comment]
Thank you for your response. Additionally, I would like to ask if data from each modality in the VQA-RAD dataset has been used, or was only the Chest X-ray modality utilized?

**Comment by ChantalMP** [comment]
For the experiments on the VQA-Rad dataset we trained and evaluated the model on the entire VQA-RAD dataset including all modalities and questions. It is important to note that this model is separate from the model we trained on our dataset (which is only xray)

**Comment by Eldo-rado** [comment]
thx～ 💕
